//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanBeYours.AdminPanel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminPanelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminPanelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanBeYours.AdminPanel.Resources.AdminPanelResource", typeof(AdminPanelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active subscription, which is why you&apos;re seeing this message..
        /// </summary>
        public static string ActiveSubscriptionMessage {
            get {
                return ResourceManager.GetString("ActiveSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Demo Thing.
        /// </summary>
        public static string CreateDemoThing {
            get {
                return ResourceManager.GetString("CreateDemoThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to implement create, update, search, and pagination for an entity across UI, application, and domain levels..
        /// </summary>
        public static string DemoImplementationInfo {
            get {
                return ResourceManager.GetString("DemoImplementationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Things.
        /// </summary>
        public static string DemoThings {
            get {
                return ResourceManager.GetString("DemoThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an active subscription, which is why you&apos;re seeing this message..
        /// </summary>
        public static string NoActiveSubscriptionMessage {
            get {
                return ResourceManager.GetString("NoActiveSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the docs.
        /// </summary>
        public static string SeeDocs {
            get {
                return ResourceManager.GetString("SeeDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed Only.
        /// </summary>
        public static string SubscribedOnly {
            get {
                return ResourceManager.GetString("SubscribedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed users only.
        /// </summary>
        public static string SubscribedUsersOnly {
            get {
                return ResourceManager.GetString("SubscribedUsersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo page shows how to check whether the currently logged-in user has an active subscription. You can use this logic to control access to your features, grant access to subscribed users and prompt others to subscribe first. For more details, see the documentation..
        /// </summary>
        public static string SubscribedUsersOnlyInfo {
            get {
                return ResourceManager.GetString("SubscribedUsersOnlyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Demo Thing.
        /// </summary>
        public static string UpdateDemoThing {
            get {
                return ResourceManager.GetString("UpdateDemoThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Available Plans.
        /// </summary>
        public static string ViewAvailablePlans {
            get {
                return ResourceManager.GetString("ViewAvailablePlans", resourceCulture);
            }
        }
    }
}
