name: Deploy to Staging

on:
  workflow_dispatch: # Trigger for manual deployment

jobs:
  # Separate job to deploy Web project
  deploy_web_staging:
    runs-on: self-hosted
    environment: staging
    steps:
      - name: Stop IIS App Pool for Web project
        run: |
          $appPoolName = "Website.Stage"  # Replace with the name of your App Pool
          Write-Host "Stopping IIS App Pool: $appPoolName"
          Stop-WebAppPool -Name $appPoolName

          # Wait for the app pool to stop
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Stopped") {
                  Write-Host "App Pool $appPoolName has successfully stopped."
                  break
              }
              Write-Host "App Pool $appPoolName is still stopping. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Stopped") {
              throw "App Pool $appPoolName did not stop within the expected time."
          }

      - name: Deploy Web project to Staging
        run: |
          # Path to the Web.zip file created in the build job
          $sourcePath = './output/Web.zip'
          $destinationPath = 'C:\Hosting\CanBeYours\Stage\Website\Web.zip'
          Copy-Item -Path $sourcePath -Destination $destinationPath
          Expand-Archive -Path $destinationPath -DestinationPath 'C:\Hosting\CanBeYours\Stage\Website' -Force

      - name: Start IIS App Pool for Web project
        run: |
          $appPoolName = "Website.Stage"  # Replace with the name of your App Pool
          Write-Host "Starting IIS App Pool: $appPoolName"
          Start-WebAppPool -Name $appPoolName

          # Wait for the app pool to start
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Started") {
                  Write-Host "App Pool $appPoolName has successfully started."
                  break
              }
              Write-Host "App Pool $appPoolName is still starting. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Started") {
              throw "App Pool $appPoolName did not start within the expected time."
          }

  # Separate job to deploy AdminPanel project
  deploy_web_admin_staging:
    runs-on: self-hosted
    environment: staging
    steps:
      - name: Stop IIS App Pool for AdminPanel project
        run: |
          $appPoolName = "Admin.Stage"  # Replace with the name of your App Pool
          Write-Host "Stopping IIS App Pool: $appPoolName"
          Stop-WebAppPool -Name $appPoolName

          # Wait for the app pool to stop
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Stopped") {
                  Write-Host "App Pool $appPoolName has successfully stopped."
                  break
              }
              Write-Host "App Pool $appPoolName is still stopping. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Stopped") {
              throw "App Pool $appPoolName did not stop within the expected time."
          }

      - name: Deploy AdminPanel project to Staging
        run: |
          # Path to the AdminPanel.zip file created in the build job
          $sourcePath = './output/AdminPanel.zip'
          $destinationPath = 'C:\Hosting\CanBeYours\Stage\Admin\AdminPanel.zip'
          Copy-Item -Path $sourcePath -Destination $destinationPath
          Expand-Archive -Path $destinationPath -DestinationPath 'C:\Hosting\CanBeYours\Stage\Admin' -Force

      - name: Start IIS App Pool for AdminPanel project
        run: |
          $appPoolName = "Admin.Stage"  # Replace with the name of your App Pool
          Write-Host "Starting IIS App Pool: $appPoolName"
          Start-WebAppPool -Name $appPoolName

          # Wait for the app pool to start
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Started") {
                  Write-Host "App Pool $appPoolName has successfully started."
                  break
              }
              Write-Host "App Pool $appPoolName is still starting. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Started") {
              throw "App Pool $appPoolName did not start within the expected time."
          }

  # Separate job to deploy AdminPanel project
  deploy_web_api_staging:
    runs-on: self-hosted
    environment: staging
    steps:
      - name: Stop IIS App Pool for Api project
        run: |
          $appPoolName = "Api.Stage"  # Replace with the name of your App Pool
          Write-Host "Stopping IIS App Pool: $appPoolName"
          Stop-WebAppPool -Name $appPoolName

          # Wait for the app pool to stop
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Stopped") {
                  Write-Host "App Pool $appPoolName has successfully stopped."
                  break
              }
              Write-Host "App Pool $appPoolName is still stopping. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Stopped") {
              throw "App Pool $appPoolName did not stop within the expected time."
          }

      - name: Deploy Api project to Staging
        run: |
          # Path to the Api.zip file created in the build job
          $sourcePath = './output/Api.zip'
          $destinationPath = 'C:\Hosting\CanBeYours\Stage\Api\Api.zip'
          Copy-Item -Path $sourcePath -Destination $destinationPath
          Expand-Archive -Path $destinationPath -DestinationPath 'C:\Hosting\CanBeYours\Stage\Api' -Force

      - name: Start IIS App Pool for Api project
        run: |
          $appPoolName = "Api.Stage"  # Replace with the name of your App Pool
          Write-Host "Starting IIS App Pool: $appPoolName"
          Start-WebAppPool -Name $appPoolName

          # Wait for the app pool to start
          $maxRetries = 10
          $retryInterval = 2
          $retries = 0
          while ($retries -lt $maxRetries) {
              $appPoolStatus = (Get-WebAppPoolState -Name $appPoolName).Value
              if ($appPoolStatus -eq "Started") {
                  Write-Host "App Pool $appPoolName has successfully started."
                  break
              }
              Write-Host "App Pool $appPoolName is still starting. Retrying in $retryInterval seconds..."
              Start-Sleep -Seconds $retryInterval
              $retries++
          }
          if ($appPoolStatus -ne "Started") {
              throw "App Pool $appPoolName did not start within the expected time."
          }
